[versions]
agp = "8.2.0-alpha15"
kotlin = "1.9.0"
circuit = "0.12.1"
lifecycle-runtime-ktx = "2.6.1"
anvil = "2.4.7"
dagger = "2.47"
ksp = "1.9.0-1.0.13"

[libraries]
androidx-activity-compose = "androidx.activity:activity-compose:1.7.2"
androidx-compose-bom = "androidx.compose:compose-bom:2023.06.01"
androidx-compose-material = { module = "androidx.compose.material:material" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-core-splashscreen = "androidx.core:core-splashscreen:1.0.1"
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
slack-circuit = { group = "com.slack.circuit", name = "circuit-foundation", version.ref = "circuit" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }


[plugins]
com-android-application = { id = "com.android.application", version.ref = "agp" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
com-squareup-anvil = { id = "com.squareup.anvil", version.ref = "anvil" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp"}
[bundles]

